/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import ClassDoiTuong.TaiKhoan;
import ClassDoiTuong.BaoCao;
import ChucNang.Client;
/*import vào Class Client có chứa các thuộc tính lưu dữ liệu bao gồm danh sách taiKhoan, danh sách thietBi, danh sách baoCao*/
import ClassDoiTuong.ThietBi;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class GiaoDienKyThuatVien extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    DefaultTableModel model;
    Client cLIENT=new Client();
    int idKTV=0;
    String tenKtv;
    public GiaoDienKyThuatVien(String tkktv) {
        initComponents();
        tenKtv = tkktv;
        HienThi luong=new HienThi();
        luong.start();
    }

    private GiaoDienKyThuatVien() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /*Hiển thị danh sách vào bản trạng thái lỗi được giao*/
    class HienThi extends Thread {

        public HienThi() {
        }

        @Override
        public void run() {
            while (true) {
                try {
                    if (Client.duLieuTaiKhoan == 1 && Client.duLieuThietBi == 1 && Client.duLieuBaoCao == 1) {
                        showktv();
                        Client.duLieuTaiKhoan = 0;
                        Client.duLieuThietBi = 0;
                        Client.duLieuBaoCao = 0;
                    }
                    this.sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(GiaoDienQuanTriVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        public final void showktv() {
//        String[] columnNames={"Nhân Viên Báo","Mã Thiết Bị","Tên","Vị Trí","Loại Lỗi","Mô Tả","Ngày Báo Cáo","Tình Trạng"};
            for(TaiKhoan tk: Client.danhSachTaiKhoan){
            if(tk.getTenNguoiDung().equals(tenKtv))idKTV=tk.getId();
        }
        System.out.println("dangw Nhap "+tenKtv);
        System.out.println("idKTV "+idKTV);
            model = (DefaultTableModel) ktv.getModel();
            model.setColumnIdentifiers(new Object[]{
                "ID", "Nhân Viên Báo", "Mã Thiết Bị", "Tên", "Vị Trí", "Loại Lỗi", "Mô Tả", "Ngày Báo Cáo", "Tình Trạng"
            });
            ktv.removeAll();
            System.out.println(Client.danhSachBaoCao.size());
            for (BaoCao baoCao : Client.danhSachBaoCao) {
                if(baoCao.getIdKyThuatVienDuocChiDinh()==idKTV){
                    TaiKhoan t = new TaiKhoan();
                for (TaiKhoan taiKhoan : Client.danhSachTaiKhoan) {
                    if (taiKhoan.getId() == baoCao.getIdNguoiBaoCao()) {
                        t = taiKhoan;
                    }
                }

                ThietBi tb = new ThietBi();
                for (ThietBi thietBi : Client.danhSachThietBi) {/*danhSachThietBi Lấy trực tiếp từ Client*/
                    if (baoCao.getIdThietBiGapSuCo() == thietBi.getId()) {
                        tb = thietBi;
                    }
                }

                model.addRow(new Object[]{
                    baoCao.getId(), t.getTenNguoiDung(), baoCao.getIdThietBiGapSuCo(), tb.getTen(), tb.getViTri(), baoCao.getLoaiSuCo(), baoCao.getMoTaSuCo(), baoCao.getThoiGian(), tb.getTrangThai()
                });
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ktv = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        upData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ktv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ktv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ktv.setEditingColumn(25);
        ktv.setRowHeight(25);
        jScrollPane3.setViewportView(ktv);

        jLabel1.setText("BẢN TRẠNG THÁI LỖI ĐƯỢC GIAO");

        upData.setText("Cập Nhật");
        upData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(upData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(289, 289, 289))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(upData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Kỹ Thuật Viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cap nhat bao cao
     *
     * @param evt
     */
    private void upDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDataActionPerformed
        /* Lay du lieu tu form */
        int idThietBi = (int) ktv.getValueAt(ktv.getSelectedRow(), 2);
        String trangThai = ktv.getValueAt(ktv.getSelectedRow(), 8).toString();
        try {
            for (ThietBi tb : Client.danhSachThietBi) {
                if (tb.getId() == idThietBi) {
                    tb.setTrangThai(trangThai);
                    Client.thietBi = new ThietBi(tb);
                }
            }
            ktv.clearSelection();
            ktv.removeAll();
            Client.guiYeuCau("TB04");
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "Chưa cập nhật được trạng thái.");
        }

    }//GEN-LAST:event_upDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKyThuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKyThuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKyThuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKyThuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienKyThuatVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable ktv;
    private javax.swing.JButton upData;
    // End of variables declaration//GEN-END:variables
}
